# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bX8x-LBEafI1kR5yRHvhYk_Gm4wEnMru
"""

!pip install kaggle
!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip chest-xray-pneumonia.zip

import os
print(os.listdir("chest_xray"))

import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import random

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

IMG_SIZE = 150

def load_data(folder):
    data = []
    for category in ["NORMAL", "PNEUMONIA"]:
        path = os.path.join(folder, category)
        label = 0 if category == "NORMAL" else 1

        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path, img))
                img_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                data.append([img_array, label])
            except:
                pass
    return data

train_data = load_data("chest_xray/train")

random.shuffle(train_data)

X = []
y = []

for features, label in train_data:
    X.append(features)
    y.append(label)

X = np.array(X) / 255.0   # normalize
y = np.array(y)

print(X.shape)
print(y.shape)

model = Sequential()

model.add(Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1, activation='sigmoid'))

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit(
    X, y,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

model.save("pneumonia_model.h5")

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Model Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend(["Train", "Validation"])
plt.show()

from sklearn.metrics import confusion_matrix, classification_report

y_pred = (model.predict(X) > 0.5).astype("int32")

print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(X[i])
    plt.title("PNEUMONIA" if y[i]==1 else "NORMAL")
    plt.axis('off')

plt.show()

labels = ["NORMAL", "PNEUMONIA"]
counts = [0, 0]

for _, label in train_data:
    counts[label] += 1

plt.bar(labels, counts)
plt.title("Class Distribution")
plt.xlabel("Classes")
plt.ylabel("Number of Images")
plt.show()

misclassified = np.where(y != y_pred.flatten())[0]

plt.figure(figsize=(10,5))
for i, idx in enumerate(misclassified[:6]):
    plt.subplot(2,3,i+1)
    plt.imshow(X[idx])
    plt.title(f"Actual: {y[idx]}, Pred: {y_pred[idx][0]}")
    plt.axis('off')

plt.show()

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

IMG_SIZE = 150

file_name = "p9t85GYhc3Umaq68hLZQ_RackMultipart20180207-1581-1xyzqzv.jpg"

img = cv2.imread(file_name)
img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Uploaded X-ray")
plt.axis('off')
plt.show()

img = img / 255.0
img = np.reshape(img, (1, IMG_SIZE, IMG_SIZE, 3))

prediction = model.predict(img)

confidence = prediction[0][0]

if confidence > 0.5:
    print(f"🩺 Pneumonia Detected ({confidence*100:.2f}%)")
else:
    print(f"✅ Normal ({(1-confidence)*100:.2f}%)")

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

IMG_SIZE = 150

file_name = "Screenshot 2026-04-07 125243.png"

img = cv2.imread(file_name)
img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Uploaded X-ray")
plt.axis('off')
plt.show()

import cv2
import numpy as np

img_path = "Screenshot 2026-04-07 125243.png"  # your file name

img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

img = cv2.resize(img, (150, 150))

img = img.reshape(1, 150, 150, 1) / 255.0

import cv2
import numpy as np

img_path = "Screenshot 2026-04-07 125243.png"

# Load as COLOR (3 channels)
img = cv2.imread(img_path)

# Resize
img = cv2.resize(img, (150, 150))

# Normalize + reshape
img = img.reshape(1, 150, 150, 3) / 255.0

# Predict
prediction = model.predict(img)

if prediction[0][0] > 0.5:
    print("🫁 PNEUMONIA")
else:
    print("✅ NORMAL")